services:
  discord-free-game-notifier:
    container_name: discord-free-game-notifier
    image: ghcr.io/thelovinator1/discord-free-game-notifier:master
    env_file:
      - .env
    environment:
      - WEBHOOK_URL=${WEBHOOK_URL}
      - LOG_LEVEL=DEBUG
    volumes:
      - discord-free-game-notifier:/home/botuser/.local/share/discord_free_game_notifier/
    restart: unless-stopped
volumes:
  discord-free-game-notifier:
